### ISSUE TITLE
Why no subshells?

### ISSUE THREAD

**Issue by Rudxain** [hyperupcall/bash-algo#1]
Is it considered "cheating"? Is it for performance?

**Comment by hyperupcall** [comment]
I would consider it cheating if done enough. But the primary reason is performance - ~~launching a subshell takes a few tenths of a second, and exec'ing out to an executable can add more~~. Bash performance is death by a thousand paper cuts.

**Comment by hyperupcall** [comment]
Here is a relevant micro benchmark: https://github.com/asdf-vm/asdf/pull/1441#discussion_r1086217001. I don't think the microbenchmark adequately shows how much things can slow down too, especially if there are loops involved.

**Comment by Rudxain** [comment]
@hyperupcall Thanks for the info. Now that I think about it, I should be using `REPLY` in my scripts
